"""physical and journal nudge fields

Revision ID: 0003
Revises: 0002
Create Date: 2026-04-26 17:21:18.268741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_band', sa.Text(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('moved', sa.Boolean(), nullable=True),
    sa.Column('movement_type', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IS NULL OR movement_type IN ('walk','workout','sport','other')", name='ck_physical_movement_type'),
    sa.CheckConstraint("sleep_band IN ('lt5','5to6','6to7','7to8','gt8')", name='ck_physical_sleep_band'),
    sa.CheckConstraint('energy IS NULL OR (energy >= 1 AND energy <= 10)', name='ck_physical_energy'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_physical_user_date')
    )
    op.create_index('idx_physical_user_date', 'physical_entries', ['user_id', 'date'], unique=False)
    op.add_column('journal_entries', sa.Column('shown_nudge_id', sa.Text(), nullable=True))
    op.add_column('journal_entries', sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'feedback')
    op.drop_column('journal_entries', 'shown_nudge_id')
    op.drop_index('idx_physical_user_date', table_name='physical_entries')
    op.drop_table('physical_entries')
    # ### end Alembic commands ###
